
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Europe/Bucharest",
    transitions: ZoneSet {
        first: ZoneDetails {
            offset: 6264,  // UTC offset 6264, DST offset 0
            name: "LMT",
        },
        rest: &[
        (-2469404664, ZoneDetails {
            offset: 6264,  // UTC offset 6264, DST offset 0
            name: "BMT",
        }),
        (-1213148664, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1187056800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1175479200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1159754400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1144029600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1127700000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1111975200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1096250400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1080525600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1064800800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1049076000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1033351200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1017626400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1001901600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-986176800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-970452000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-954727200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (296604000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (307486800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (323816400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (338940000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (354672000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (370396800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (386121600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (401846400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (417571200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (433296000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (449020800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (465350400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (481075200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (496800000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (512524800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (528249600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (543974400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (559699200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (575424000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (591148800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (606873600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (622598400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (638323200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (654652800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (670370400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (686095200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (701820000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (717544800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (733269600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (748994400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (764719200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (780440400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (796168800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (811890000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (828223200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (846363600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (859683600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (877827600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (891133200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (909277200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (922582800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (941331600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (954032400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (972781200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (985482000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1004230800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1017536400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1035680400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1048986000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1067130000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1080435600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1099184400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1111885200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1130634000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1143334800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1162083600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1174784400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1193533200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1206838800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1224982800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1238288400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1256432400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1269738000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1288486800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1301187600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1319936400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1332637200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1351386000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1364691600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1382835600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1396141200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1414285200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1427590800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1445734800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1459040400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1477789200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1490490000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1509238800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1521939600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1540688400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1553994000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1572138000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1585443600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1603587600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1616893200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1635642000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1648342800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1667091600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1679792400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1698541200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1711846800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1729990800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1743296400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1761440400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1774746000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1792890000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1806195600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1824944400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1837645200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1856394000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1869094800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1887843600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1901149200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1919293200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1932598800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1950742800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1964048400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1982797200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1995498000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2014246800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2026947600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2045696400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2058397200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2077146000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2090451600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2108595600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2121901200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2140045200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2153350800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2172099600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2184800400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2203549200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2216250000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2234998800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2248304400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2266448400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2279754000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2297898000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2311203600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2329347600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2342653200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2361402000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2374102800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2392851600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2405552400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2424301200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2437606800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2455750800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2469056400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2487200400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2500506000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2519254800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2531955600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2550704400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2563405200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2582154000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2595459600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2613603600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2626909200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2645053200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2658358800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2676502800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2689808400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2708557200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2721258000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2740006800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2752707600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2771456400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2784762000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2802906000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2816211600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2834355600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2847661200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2866410000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2879110800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2897859600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2910560400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2929309200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2942010000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2960758800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2974064400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2992208400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3005514000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3023658000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3036963600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3055712400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3068413200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3087162000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3099862800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3118611600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3131917200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3150061200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3163366800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3181510800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3194816400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3212960400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3226266000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3245014800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3257715600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3276464400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3289165200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3307914000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3321219600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3339363600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3352669200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3370813200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3384118800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3402867600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3415568400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3434317200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3447018000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3465766800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3479072400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3497216400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3510522000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3528666000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3541971600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3560115600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3573421200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3592170000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3604870800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3623619600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3636320400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3655069200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3668374800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3686518800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3699824400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3717968400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3731274000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3750022800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3762723600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3781472400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3794173200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3812922000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3825622800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3844371600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3857677200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3875821200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3889126800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3907270800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3920576400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3939325200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3952026000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3970774800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3983475600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (4002224400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (4015530000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (4033674000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (4046979600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (4065123600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (4078429200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (4096573200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
    ]},
};


