
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zone::{TimeZone, FixedTimespanSet, FixedTimespan};

pub const ZONE: TimeZone<'static> = TimeZone {
    name: "Europe/Lisbon",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: 2205,  // UTC offset 2205, DST offset 0
            is_dst: false,
            name:   "LMT",
        },
        rest: &[
        (-1830386205, FixedTimespan {  // 1911-11-31T23-23-15 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1689555600, FixedTimespan {  // 1916-05-17T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1677801600, FixedTimespan {  // 1916-10-01T0-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1667437200, FixedTimespan {  // 1917-01-28T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1647738000, FixedTimespan {  // 1917-09-14T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1635814800, FixedTimespan {  // 1918-02-01T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1616202000, FixedTimespan {  // 1918-09-14T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1604365200, FixedTimespan {  // 1919-01-28T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1584666000, FixedTimespan {  // 1919-09-14T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1572656400, FixedTimespan {  // 1920-02-01T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1553043600, FixedTimespan {  // 1920-09-14T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1541206800, FixedTimespan {  // 1921-01-28T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1521507600, FixedTimespan {  // 1921-09-14T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1442451600, FixedTimespan {  // 1924-03-16T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1426813200, FixedTimespan {  // 1924-09-14T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1379293200, FixedTimespan {  // 1926-03-17T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1364778000, FixedTimespan {  // 1926-09-02T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1348448400, FixedTimespan {  // 1927-03-09T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1333328400, FixedTimespan {  // 1927-09-01T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1316394000, FixedTimespan {  // 1928-03-14T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1301274000, FixedTimespan {  // 1928-09-06T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1284339600, FixedTimespan {  // 1929-03-20T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1269824400, FixedTimespan {  // 1929-09-05T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1221440400, FixedTimespan {  // 1931-03-18T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1206925200, FixedTimespan {  // 1931-09-03T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1191200400, FixedTimespan {  // 1932-03-02T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1175475600, FixedTimespan {  // 1932-09-01T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1127696400, FixedTimespan {  // 1934-03-07T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1111971600, FixedTimespan {  // 1934-09-06T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1096851600, FixedTimespan {  // 1935-02-30T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1080522000, FixedTimespan {  // 1935-09-05T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1063587600, FixedTimespan {  // 1936-03-18T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1049072400, FixedTimespan {  // 1936-09-03T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1033347600, FixedTimespan {  // 1937-03-03T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-1017622800, FixedTimespan {  // 1937-09-02T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-1002502800, FixedTimespan {  // 1938-02-26T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-986173200, FixedTimespan {  // 1938-09-01T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-969238800, FixedTimespan {  // 1939-03-15T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-950490000, FixedTimespan {  // 1939-10-18T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-942022800, FixedTimespan {  // 1940-01-24T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-922669200, FixedTimespan {  // 1940-09-05T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-906944400, FixedTimespan {  // 1941-03-05T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-891133200, FixedTimespan {  // 1941-09-05T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-877309200, FixedTimespan {  // 1942-02-14T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-873684000, FixedTimespan {  // 1942-03-25T22-00-00 UTC
            offset: 7200,  // UTC offset 0, DST offset 7200
            is_dst: true,
            name:   "WEMT",
        }),
        (-864007200, FixedTimespan {  // 1942-07-15T22-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-857955600, FixedTimespan {  // 1942-09-24T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-845859600, FixedTimespan {  // 1943-02-13T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-842839200, FixedTimespan {  // 1943-03-17T22-00-00 UTC
            offset: 7200,  // UTC offset 0, DST offset 7200
            is_dst: true,
            name:   "WEMT",
        }),
        (-831348000, FixedTimespan {  // 1943-07-28T22-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-825901200, FixedTimespan {  // 1943-09-30T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-814410000, FixedTimespan {  // 1944-02-11T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-810784800, FixedTimespan {  // 1944-03-22T22-00-00 UTC
            offset: 7200,  // UTC offset 0, DST offset 7200
            is_dst: true,
            name:   "WEMT",
        }),
        (-799898400, FixedTimespan {  // 1944-07-26T22-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-794451600, FixedTimespan {  // 1944-09-28T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-782960400, FixedTimespan {  // 1945-02-10T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-779335200, FixedTimespan {  // 1945-03-21T22-00-00 UTC
            offset: 7200,  // UTC offset 0, DST offset 7200
            is_dst: true,
            name:   "WEMT",
        }),
        (-768448800, FixedTimespan {  // 1945-07-25T22-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-763002000, FixedTimespan {  // 1945-09-27T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-749091600, FixedTimespan {  // 1946-03-06T23-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-733366800, FixedTimespan {  // 1946-09-05T23-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-717631200, FixedTimespan {  // 1947-03-06T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-701906400, FixedTimespan {  // 1947-09-05T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-686181600, FixedTimespan {  // 1948-03-04T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-670456800, FixedTimespan {  // 1948-09-03T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-654732000, FixedTimespan {  // 1949-03-03T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-639007200, FixedTimespan {  // 1949-09-02T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-591832800, FixedTimespan {  // 1951-03-01T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-575503200, FixedTimespan {  // 1951-09-07T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-559778400, FixedTimespan {  // 1952-03-06T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-544053600, FixedTimespan {  // 1952-09-05T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-528328800, FixedTimespan {  // 1953-03-05T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-512604000, FixedTimespan {  // 1953-09-04T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-496879200, FixedTimespan {  // 1954-03-04T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-481154400, FixedTimespan {  // 1954-09-03T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-465429600, FixedTimespan {  // 1955-03-03T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-449704800, FixedTimespan {  // 1955-09-02T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-433980000, FixedTimespan {  // 1956-03-01T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-417650400, FixedTimespan {  // 1956-09-07T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-401925600, FixedTimespan {  // 1957-03-07T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-386200800, FixedTimespan {  // 1957-09-06T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-370476000, FixedTimespan {  // 1958-03-06T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-354751200, FixedTimespan {  // 1958-09-05T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-339026400, FixedTimespan {  // 1959-03-05T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-323301600, FixedTimespan {  // 1959-09-04T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-307576800, FixedTimespan {  // 1960-03-03T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-291852000, FixedTimespan {  // 1960-09-02T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-276127200, FixedTimespan {  // 1961-03-02T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-260402400, FixedTimespan {  // 1961-09-01T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-244677600, FixedTimespan {  // 1962-03-01T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-228348000, FixedTimespan {  // 1962-09-07T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-212623200, FixedTimespan {  // 1963-03-07T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-196898400, FixedTimespan {  // 1963-09-06T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-181173600, FixedTimespan {  // 1964-03-05T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-165448800, FixedTimespan {  // 1964-09-04T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-149724000, FixedTimespan {  // 1965-03-04T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (-133999200, FixedTimespan {  // 1965-09-03T2-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (-118274400, FixedTimespan {  // 1966-03-03T2-00-00 UTC
            offset: 3600,  // UTC offset 3600, DST offset 0
            is_dst: false,
            name:   "CET",
        }),
        (212544000, FixedTimespan {  // 1976-08-26T0-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (228268800, FixedTimespan {  // 1977-02-27T0-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (243993600, FixedTimespan {  // 1977-08-25T0-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (260323200, FixedTimespan {  // 1978-03-02T0-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (276048000, FixedTimespan {  // 1978-09-01T0-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (291772800, FixedTimespan {  // 1979-03-01T0-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (307501200, FixedTimespan {  // 1979-08-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (323222400, FixedTimespan {  // 1980-02-30T0-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (338950800, FixedTimespan {  // 1980-08-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (354675600, FixedTimespan {  // 1981-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (370400400, FixedTimespan {  // 1981-08-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (386125200, FixedTimespan {  // 1982-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (401850000, FixedTimespan {  // 1982-08-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (417578400, FixedTimespan {  // 1983-02-27T2-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (433299600, FixedTimespan {  // 1983-08-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (449024400, FixedTimespan {  // 1984-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (465354000, FixedTimespan {  // 1984-08-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (481078800, FixedTimespan {  // 1985-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (496803600, FixedTimespan {  // 1985-08-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (512528400, FixedTimespan {  // 1986-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (528253200, FixedTimespan {  // 1986-08-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (543978000, FixedTimespan {  // 1987-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (559702800, FixedTimespan {  // 1987-08-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (575427600, FixedTimespan {  // 1988-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (591152400, FixedTimespan {  // 1988-08-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (606877200, FixedTimespan {  // 1989-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (622602000, FixedTimespan {  // 1989-08-24T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (638326800, FixedTimespan {  // 1990-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (654656400, FixedTimespan {  // 1990-08-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (670381200, FixedTimespan {  // 1991-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (686106000, FixedTimespan {  // 1991-08-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (701830800, FixedTimespan {  // 1992-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (717552000, FixedTimespan {  // 1992-08-27T0-00-00 UTC
            offset: 7200,  // UTC offset 3600, DST offset 3600
            is_dst: true,
            name:   "CEST",
        }),
        (717555600, FixedTimespan {  // 1992-08-27T1-00-00 UTC
            offset: 3600,  // UTC offset 3600, DST offset 0
            is_dst: false,
            name:   "CET",
        }),
        (733280400, FixedTimespan {  // 1993-02-28T1-00-00 UTC
            offset: 7200,  // UTC offset 3600, DST offset 3600
            is_dst: true,
            name:   "CEST",
        }),
        (749005200, FixedTimespan {  // 1993-08-26T1-00-00 UTC
            offset: 3600,  // UTC offset 3600, DST offset 0
            is_dst: false,
            name:   "CET",
        }),
        (764730000, FixedTimespan {  // 1994-02-27T1-00-00 UTC
            offset: 7200,  // UTC offset 3600, DST offset 3600
            is_dst: true,
            name:   "CEST",
        }),
        (780454800, FixedTimespan {  // 1994-08-25T1-00-00 UTC
            offset: 3600,  // UTC offset 3600, DST offset 0
            is_dst: false,
            name:   "CET",
        }),
        (796179600, FixedTimespan {  // 1995-02-26T1-00-00 UTC
            offset: 7200,  // UTC offset 3600, DST offset 3600
            is_dst: true,
            name:   "CEST",
        }),
        (811904400, FixedTimespan {  // 1995-08-24T1-00-00 UTC
            offset: 3600,  // UTC offset 3600, DST offset 0
            is_dst: false,
            name:   "CET",
        }),
        (828230400, FixedTimespan {  // 1996-02-31T0-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (846378000, FixedTimespan {  // 1996-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (859683600, FixedTimespan {  // 1997-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (877827600, FixedTimespan {  // 1997-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (891133200, FixedTimespan {  // 1998-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (909277200, FixedTimespan {  // 1998-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (922582800, FixedTimespan {  // 1999-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (941331600, FixedTimespan {  // 1999-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (954032400, FixedTimespan {  // 2000-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (972781200, FixedTimespan {  // 2000-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (985482000, FixedTimespan {  // 2001-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1004230800, FixedTimespan {  // 2001-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1017536400, FixedTimespan {  // 2002-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1035680400, FixedTimespan {  // 2002-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1048986000, FixedTimespan {  // 2003-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1067130000, FixedTimespan {  // 2003-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1080435600, FixedTimespan {  // 2004-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1099184400, FixedTimespan {  // 2004-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1111885200, FixedTimespan {  // 2005-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1130634000, FixedTimespan {  // 2005-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1143334800, FixedTimespan {  // 2006-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1162083600, FixedTimespan {  // 2006-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1174784400, FixedTimespan {  // 2007-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1193533200, FixedTimespan {  // 2007-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1206838800, FixedTimespan {  // 2008-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1224982800, FixedTimespan {  // 2008-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1238288400, FixedTimespan {  // 2009-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1256432400, FixedTimespan {  // 2009-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1269738000, FixedTimespan {  // 2010-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1288486800, FixedTimespan {  // 2010-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1301187600, FixedTimespan {  // 2011-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1319936400, FixedTimespan {  // 2011-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1332637200, FixedTimespan {  // 2012-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1351386000, FixedTimespan {  // 2012-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1364691600, FixedTimespan {  // 2013-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1382835600, FixedTimespan {  // 2013-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1396141200, FixedTimespan {  // 2014-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1414285200, FixedTimespan {  // 2014-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1427590800, FixedTimespan {  // 2015-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1445734800, FixedTimespan {  // 2015-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1459040400, FixedTimespan {  // 2016-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1477789200, FixedTimespan {  // 2016-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1490490000, FixedTimespan {  // 2017-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1509238800, FixedTimespan {  // 2017-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1521939600, FixedTimespan {  // 2018-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1540688400, FixedTimespan {  // 2018-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1553994000, FixedTimespan {  // 2019-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1572138000, FixedTimespan {  // 2019-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1585443600, FixedTimespan {  // 2020-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1603587600, FixedTimespan {  // 2020-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1616893200, FixedTimespan {  // 2021-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1635642000, FixedTimespan {  // 2021-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1648342800, FixedTimespan {  // 2022-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1667091600, FixedTimespan {  // 2022-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1679792400, FixedTimespan {  // 2023-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1698541200, FixedTimespan {  // 2023-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1711846800, FixedTimespan {  // 2024-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1729990800, FixedTimespan {  // 2024-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1743296400, FixedTimespan {  // 2025-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1761440400, FixedTimespan {  // 2025-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1774746000, FixedTimespan {  // 2026-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1792890000, FixedTimespan {  // 2026-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1806195600, FixedTimespan {  // 2027-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1824944400, FixedTimespan {  // 2027-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1837645200, FixedTimespan {  // 2028-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1856394000, FixedTimespan {  // 2028-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1869094800, FixedTimespan {  // 2029-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1887843600, FixedTimespan {  // 2029-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1901149200, FixedTimespan {  // 2030-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1919293200, FixedTimespan {  // 2030-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1932598800, FixedTimespan {  // 2031-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1950742800, FixedTimespan {  // 2031-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1964048400, FixedTimespan {  // 2032-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (1982797200, FixedTimespan {  // 2032-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (1995498000, FixedTimespan {  // 2033-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2014246800, FixedTimespan {  // 2033-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2026947600, FixedTimespan {  // 2034-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2045696400, FixedTimespan {  // 2034-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2058397200, FixedTimespan {  // 2035-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2077146000, FixedTimespan {  // 2035-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2090451600, FixedTimespan {  // 2036-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2108595600, FixedTimespan {  // 2036-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2121901200, FixedTimespan {  // 2037-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2140045200, FixedTimespan {  // 2037-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2153350800, FixedTimespan {  // 2038-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2172099600, FixedTimespan {  // 2038-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2184800400, FixedTimespan {  // 2039-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2203549200, FixedTimespan {  // 2039-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2216250000, FixedTimespan {  // 2040-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2234998800, FixedTimespan {  // 2040-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2248304400, FixedTimespan {  // 2041-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2266448400, FixedTimespan {  // 2041-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2279754000, FixedTimespan {  // 2042-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2297898000, FixedTimespan {  // 2042-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2311203600, FixedTimespan {  // 2043-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2329347600, FixedTimespan {  // 2043-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2342653200, FixedTimespan {  // 2044-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2361402000, FixedTimespan {  // 2044-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2374102800, FixedTimespan {  // 2045-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2392851600, FixedTimespan {  // 2045-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2405552400, FixedTimespan {  // 2046-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2424301200, FixedTimespan {  // 2046-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2437606800, FixedTimespan {  // 2047-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2455750800, FixedTimespan {  // 2047-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2469056400, FixedTimespan {  // 2048-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2487200400, FixedTimespan {  // 2048-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2500506000, FixedTimespan {  // 2049-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2519254800, FixedTimespan {  // 2049-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2531955600, FixedTimespan {  // 2050-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2550704400, FixedTimespan {  // 2050-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2563405200, FixedTimespan {  // 2051-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2582154000, FixedTimespan {  // 2051-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2595459600, FixedTimespan {  // 2052-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2613603600, FixedTimespan {  // 2052-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2626909200, FixedTimespan {  // 2053-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2645053200, FixedTimespan {  // 2053-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2658358800, FixedTimespan {  // 2054-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2676502800, FixedTimespan {  // 2054-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2689808400, FixedTimespan {  // 2055-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2708557200, FixedTimespan {  // 2055-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2721258000, FixedTimespan {  // 2056-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2740006800, FixedTimespan {  // 2056-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2752707600, FixedTimespan {  // 2057-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2771456400, FixedTimespan {  // 2057-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2784762000, FixedTimespan {  // 2058-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2802906000, FixedTimespan {  // 2058-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2816211600, FixedTimespan {  // 2059-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2834355600, FixedTimespan {  // 2059-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2847661200, FixedTimespan {  // 2060-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2866410000, FixedTimespan {  // 2060-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2879110800, FixedTimespan {  // 2061-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2897859600, FixedTimespan {  // 2061-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2910560400, FixedTimespan {  // 2062-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2929309200, FixedTimespan {  // 2062-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2942010000, FixedTimespan {  // 2063-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2960758800, FixedTimespan {  // 2063-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (2974064400, FixedTimespan {  // 2064-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (2992208400, FixedTimespan {  // 2064-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3005514000, FixedTimespan {  // 2065-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3023658000, FixedTimespan {  // 2065-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3036963600, FixedTimespan {  // 2066-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3055712400, FixedTimespan {  // 2066-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3068413200, FixedTimespan {  // 2067-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3087162000, FixedTimespan {  // 2067-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3099862800, FixedTimespan {  // 2068-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3118611600, FixedTimespan {  // 2068-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3131917200, FixedTimespan {  // 2069-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3150061200, FixedTimespan {  // 2069-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3163366800, FixedTimespan {  // 2070-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3181510800, FixedTimespan {  // 2070-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3194816400, FixedTimespan {  // 2071-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3212960400, FixedTimespan {  // 2071-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3226266000, FixedTimespan {  // 2072-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3245014800, FixedTimespan {  // 2072-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3257715600, FixedTimespan {  // 2073-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3276464400, FixedTimespan {  // 2073-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3289165200, FixedTimespan {  // 2074-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3307914000, FixedTimespan {  // 2074-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3321219600, FixedTimespan {  // 2075-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3339363600, FixedTimespan {  // 2075-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3352669200, FixedTimespan {  // 2076-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3370813200, FixedTimespan {  // 2076-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3384118800, FixedTimespan {  // 2077-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3402867600, FixedTimespan {  // 2077-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3415568400, FixedTimespan {  // 2078-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3434317200, FixedTimespan {  // 2078-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3447018000, FixedTimespan {  // 2079-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3465766800, FixedTimespan {  // 2079-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3479072400, FixedTimespan {  // 2080-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3497216400, FixedTimespan {  // 2080-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3510522000, FixedTimespan {  // 2081-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3528666000, FixedTimespan {  // 2081-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3541971600, FixedTimespan {  // 2082-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3560115600, FixedTimespan {  // 2082-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3573421200, FixedTimespan {  // 2083-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3592170000, FixedTimespan {  // 2083-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3604870800, FixedTimespan {  // 2084-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3623619600, FixedTimespan {  // 2084-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3636320400, FixedTimespan {  // 2085-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3655069200, FixedTimespan {  // 2085-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3668374800, FixedTimespan {  // 2086-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3686518800, FixedTimespan {  // 2086-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3699824400, FixedTimespan {  // 2087-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3717968400, FixedTimespan {  // 2087-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3731274000, FixedTimespan {  // 2088-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3750022800, FixedTimespan {  // 2088-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3762723600, FixedTimespan {  // 2089-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3781472400, FixedTimespan {  // 2089-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3794173200, FixedTimespan {  // 2090-02-26T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3812922000, FixedTimespan {  // 2090-09-29T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3825622800, FixedTimespan {  // 2091-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3844371600, FixedTimespan {  // 2091-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3857677200, FixedTimespan {  // 2092-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3875821200, FixedTimespan {  // 2092-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3889126800, FixedTimespan {  // 2093-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3907270800, FixedTimespan {  // 2093-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3920576400, FixedTimespan {  // 2094-02-28T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3939325200, FixedTimespan {  // 2094-09-31T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3952026000, FixedTimespan {  // 2095-02-27T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (3970774800, FixedTimespan {  // 2095-09-30T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (3983475600, FixedTimespan {  // 2096-02-25T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (4002224400, FixedTimespan {  // 2096-09-28T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (4015530000, FixedTimespan {  // 2097-02-31T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (4033674000, FixedTimespan {  // 2097-09-27T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (4046979600, FixedTimespan {  // 2098-02-30T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (4065123600, FixedTimespan {  // 2098-09-26T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
        (4078429200, FixedTimespan {  // 2099-02-29T1-00-00 UTC
            offset: 3600,  // UTC offset 0, DST offset 3600
            is_dst: true,
            name:   "WEST",
        }),
        (4096573200, FixedTimespan {  // 2099-09-25T1-00-00 UTC
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   "WET",
        }),
    ]},
};


