
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Europe/Lisbon",
    transitions: ZoneSet {
        first: ZoneDetails {
            offset: 2205,  // UTC offset 2205, DST offset 0
            name: "LMT",
        },
        rest: &[
        (-1830386205, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1689555600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1677801600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1667437200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1647738000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1635814800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1616202000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1604365200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1584666000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1572656400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1553043600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1541206800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1521507600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1442451600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1426813200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1379293200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1364778000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1348448400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1333328400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1316394000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1301274000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1284339600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1269824400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1221440400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1206925200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1191200400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1175475600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1127696400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1111971600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1096851600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1080522000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1063587600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1049072400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1033347600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-1017622800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-1002502800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-986173200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-969238800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-950490000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-942022800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-922669200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-906944400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-891133200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-877309200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-873684000, ZoneDetails {
            offset: 7200,  // UTC offset 0, DST offset 7200
            name: "WEMT",
        }),
        (-864007200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-857955600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-845859600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-842839200, ZoneDetails {
            offset: 7200,  // UTC offset 0, DST offset 7200
            name: "WEMT",
        }),
        (-831348000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-825901200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-814410000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-810784800, ZoneDetails {
            offset: 7200,  // UTC offset 0, DST offset 7200
            name: "WEMT",
        }),
        (-799898400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-794451600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-782960400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-779335200, ZoneDetails {
            offset: 7200,  // UTC offset 0, DST offset 7200
            name: "WEMT",
        }),
        (-768448800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-763002000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-749091600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-733366800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-717631200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-701906400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-686181600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-670456800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-654732000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-639007200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-591832800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-575503200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-559778400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-544053600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-528328800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-512604000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-496879200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-481154400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-465429600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-449704800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-433980000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-417650400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-401925600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-386200800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-370476000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-354751200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-339026400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-323301600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-307576800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-291852000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-276127200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-260402400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-244677600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-228348000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-212623200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-196898400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-181173600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-165448800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-149724000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (-133999200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (-118274400, ZoneDetails {
            offset: 3600,  // UTC offset 3600, DST offset 0
            name: "CET",
        }),
        (212544000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (228268800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (243993600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (260323200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (276048000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (291772800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (307501200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (323222400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (338950800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (354675600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (370400400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (386125200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (401850000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (417578400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (433299600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (449024400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (465354000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (481078800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (496803600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (512528400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (528253200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (543978000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (559702800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (575427600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (591152400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (606877200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (622602000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (638326800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (654656400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (670381200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (686106000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (701830800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (717552000, ZoneDetails {
            offset: 7200,  // UTC offset 3600, DST offset 3600
            name: "CEST",
        }),
        (717555600, ZoneDetails {
            offset: 3600,  // UTC offset 3600, DST offset 0
            name: "CET",
        }),
        (733280400, ZoneDetails {
            offset: 7200,  // UTC offset 3600, DST offset 3600
            name: "CEST",
        }),
        (749005200, ZoneDetails {
            offset: 3600,  // UTC offset 3600, DST offset 0
            name: "CET",
        }),
        (764730000, ZoneDetails {
            offset: 7200,  // UTC offset 3600, DST offset 3600
            name: "CEST",
        }),
        (780454800, ZoneDetails {
            offset: 3600,  // UTC offset 3600, DST offset 0
            name: "CET",
        }),
        (796179600, ZoneDetails {
            offset: 7200,  // UTC offset 3600, DST offset 3600
            name: "CEST",
        }),
        (811904400, ZoneDetails {
            offset: 3600,  // UTC offset 3600, DST offset 0
            name: "CET",
        }),
        (828230400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (846378000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (859683600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (877827600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (891133200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (909277200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (922582800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (941331600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (954032400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (972781200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (985482000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1004230800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1017536400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1035680400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1048986000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1067130000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1080435600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1099184400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1111885200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1130634000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1143334800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1162083600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1174784400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1193533200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1206838800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1224982800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1238288400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1256432400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1269738000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1288486800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1301187600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1319936400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1332637200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1351386000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1364691600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1382835600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1396141200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1414285200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1427590800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1445734800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1459040400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1477789200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1490490000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1509238800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1521939600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1540688400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1553994000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1572138000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1585443600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1603587600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1616893200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1635642000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1648342800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1667091600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1679792400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1698541200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1711846800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1729990800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1743296400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1761440400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1774746000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1792890000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1806195600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1824944400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1837645200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1856394000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1869094800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1887843600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1901149200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1919293200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1932598800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1950742800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1964048400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (1982797200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (1995498000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2014246800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2026947600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2045696400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2058397200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2077146000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2090451600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2108595600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2121901200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2140045200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2153350800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2172099600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2184800400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2203549200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2216250000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2234998800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2248304400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2266448400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2279754000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2297898000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2311203600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2329347600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2342653200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2361402000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2374102800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2392851600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2405552400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2424301200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2437606800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2455750800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2469056400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2487200400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2500506000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2519254800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2531955600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2550704400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2563405200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2582154000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2595459600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2613603600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2626909200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2645053200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2658358800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2676502800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2689808400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2708557200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2721258000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2740006800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2752707600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2771456400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2784762000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2802906000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2816211600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2834355600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2847661200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2866410000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2879110800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2897859600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2910560400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2929309200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2942010000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2960758800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (2974064400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (2992208400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3005514000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3023658000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3036963600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3055712400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3068413200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3087162000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3099862800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3118611600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3131917200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3150061200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3163366800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3181510800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3194816400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3212960400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3226266000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3245014800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3257715600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3276464400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3289165200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3307914000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3321219600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3339363600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3352669200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3370813200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3384118800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3402867600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3415568400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3434317200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3447018000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3465766800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3479072400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3497216400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3510522000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3528666000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3541971600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3560115600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3573421200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3592170000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3604870800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3623619600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3636320400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3655069200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3668374800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3686518800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3699824400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3717968400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3731274000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3750022800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3762723600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3781472400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3794173200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3812922000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3825622800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3844371600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3857677200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3875821200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3889126800, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3907270800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3920576400, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3939325200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3952026000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (3970774800, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (3983475600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (4002224400, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (4015530000, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (4033674000, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (4046979600, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (4065123600, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
        (4078429200, ZoneDetails {
            offset: 3600,  // UTC offset 0, DST offset 3600
            name: "WEST",
        }),
        (4096573200, ZoneDetails {
            offset: 0,  // UTC offset 0, DST offset 0
            name: "WET",
        }),
    ]},
};


