
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "Indian/Mahe",
    timespans: &[
        Timespan {
            offset: 13308,
            format: "LMT",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(-2006640000),
        },
        Timespan {
            offset: 14400,
            format: "SCT",
            saving: Saving::NoSaving,
            start_time: Some(-2006640000),
            end_time:   None,
        },
    ],
};


