
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Pacific/Honolulu",
    transitions: ZoneSet {
        first: ZoneDetails {
            offset: -34114,  // UTC offset -34114, DST offset 0
            name: "LMT",
        },
        rest: &[
        (-2334105086, ZoneDetails {
            offset: -34200,  // UTC offset -34200, DST offset 0
            name: "HST",
        }),
        (-1157286600, ZoneDetails {
            offset: -30600,  // UTC offset -34200, DST offset 3600
            name: "HDT",
        }),
        (-1155439800, ZoneDetails {
            offset: -34200,  // UTC offset -34200, DST offset 0
            name: "HST",
        }),
        (-880201800, ZoneDetails {
            offset: -30600,  // UTC offset -34200, DST offset 3600
            name: "HDT",
        }),
        (-765379800, ZoneDetails {
            offset: -34200,  // UTC offset -34200, DST offset 0
            name: "HST",
        }),
        (-712153800, ZoneDetails {
            offset: -36000,  // UTC offset -36000, DST offset 0
            name: "HST",
        }),
    ]},
};


