
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Pacific/Palau",
    transitions: &[
        Transition { occurs_at: None, utc_offset: 32276, dst_offset: 0, name: "LMT" },
        Transition { occurs_at: Some(-2177485076), utc_offset: 32400, dst_offset: 0, name: "PWT" },
    ],
};


