
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "Pacific/Port_Moresby",
    timespans: &[
        Timespan {
            offset: 35320,
            format: "LMT",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(-2840140800),
        },
        Timespan {
            offset: 35312,
            format: "PMMT",
            saving: Saving::NoSaving,
            start_time: Some(-2840140800),
            end_time:   Some(-2366755200),
        },
        Timespan {
            offset: 36000,
            format: "PGT",
            saving: Saving::NoSaving,
            start_time: Some(-2366755200),
            end_time:   None,
        },
    ],
};


