
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "Antarctica/Troll",
    timespans: &[
        Timespan {
            offset: 0,
            format: "zzz",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(1108166400),
        },
        Timespan {
            offset: 0,
            format: "%s",
            saving: Saving::Multiple(&rulesets::Troll),
            start_time: Some(1108166400),
            end_time:   None,
        },
    ],
};


