
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Asia/Beirut",
    transitions: ZoneSet {
        first: ZoneDetails {
            offset: 8520,  // UTC offset 8520, DST offset 0
            name: "LMT",
        },
        rest: &[
        (-2840149320, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1570413600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1552186800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1538359200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1522551600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1507514400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1490583600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-1473645600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-1460948400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-399866400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-386650800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-368330400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-355114800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-336794400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-323578800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-305172000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-291956400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (-273636000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (-260420400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (78012000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (86734800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (105055200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (118270800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (136591200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (149806800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (168127200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (181342800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (199749600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (212965200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (231285600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (244501200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (262735200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (275950800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (452210400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (466722000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (483746400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (498258000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (515282400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (529794000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (546818400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (561330000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (581119200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (592952400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (610754400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (624488400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (641512800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (656024400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (673048800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (687560400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (704671200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (718146000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (733269600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (748990800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (764719200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (780440400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (796168800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (811890000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (828223200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (843944400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (859672800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (875394000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (891122400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (906843600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (922572000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (941317200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (954021600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (972766800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (985471200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1004216400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1017525600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1035666000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1048975200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1067115600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1080424800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1099170000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1111874400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1130619600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1143324000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1162069200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1174773600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1193518800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1206828000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1224968400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1238277600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1256418000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1269727200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1288472400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1301176800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1319922000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1332626400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1351371600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1364680800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1382821200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1396130400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1414270800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1427580000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1445720400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1459029600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1477774800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1490479200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1509224400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1521928800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1540674000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1553983200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1572123600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1585432800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1603573200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1616882400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1635627600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1648332000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1667077200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1679781600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1698526800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1711836000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1729976400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1743285600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1761426000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1774735200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1792875600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1806184800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1824930000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1837634400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1856379600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1869084000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1887829200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1901138400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1919278800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1932588000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1950728400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1964037600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (1982782800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (1995487200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2014232400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2026936800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2045682000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2058386400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2077131600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2090440800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2108581200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2121890400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2140030800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2153340000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2172085200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2184789600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2203534800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2216239200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2234984400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2248293600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2266434000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2279743200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2297883600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2311192800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2329333200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2342642400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2361387600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2374092000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2392837200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2405541600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2424286800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2437596000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2455736400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2469045600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2487186000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2500495200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2519240400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2531944800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2550690000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2563394400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2582139600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2595448800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2613589200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2626898400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2645038800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2658348000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2676488400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2689797600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2708542800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2721247200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2739992400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2752696800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2771442000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2784751200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2802891600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2816200800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2834341200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2847650400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2866395600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2879100000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2897845200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2910549600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2929294800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2941999200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2960744400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (2974053600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (2992194000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3005503200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3023643600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3036952800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3055698000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3068402400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3087147600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3099852000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3118597200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3131906400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3150046800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3163356000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3181496400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3194805600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3212946000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3226255200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3245000400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3257704800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3276450000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3289154400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3307899600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3321208800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3339349200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3352658400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3370798800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3384108000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3402853200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3415557600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3434302800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3447007200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3465752400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3479061600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3497202000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3510511200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3528651600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3541960800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3560101200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3573410400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3592155600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3604860000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3623605200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3636309600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3655054800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3668364000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3686504400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3699813600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3717954000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3731263200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3750008400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3762712800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3781458000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3794162400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3812907600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3825612000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3844357200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3857666400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3875806800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3889116000, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3907256400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3920565600, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3939310800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3952015200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (3970760400, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (3983464800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (4002210000, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (4015519200, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (4033659600, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (4046968800, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (4065109200, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
        (4078418400, ZoneDetails {
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "EEST",
        }),
        (4096558800, ZoneDetails {
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "EET",
        }),
    ]},
};


