
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "Asia/Gaza",
    timespans: &[
        Timespan {
            offset: 8272,
            format: "LMT",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(-2185401600),
        },
        Timespan {
            offset: 7200,
            format: "EET",
            saving: Saving::Multiple(&rulesets::Zion),
            start_time: Some(-2185401600),
            end_time:   Some(-682646400),
        },
        Timespan {
            offset: 7200,
            format: "EE%sT",
            saving: Saving::Multiple(&rulesets::EgyptAsia),
            start_time: Some(-682646400),
            end_time:   Some(-81302400),
        },
        Timespan {
            offset: 7200,
            format: "I%sT",
            saving: Saving::Multiple(&rulesets::Zion),
            start_time: Some(-81302400),
            end_time:   Some(820454400),
        },
        Timespan {
            offset: 7200,
            format: "EE%sT",
            saving: Saving::Multiple(&rulesets::Jordan),
            start_time: Some(820454400),
            end_time:   Some(915148800),
        },
        Timespan {
            offset: 7200,
            format: "EE%sT",
            saving: Saving::Multiple(&rulesets::Palestine),
            start_time: Some(915148800),
            end_time:   Some(1219968000),
        },
        Timespan {
            offset: 7200,
            format: "EET",
            saving: Saving::NoSaving,
            start_time: Some(1219968000),
            end_time:   Some(1220227200),
        },
        Timespan {
            offset: 7200,
            format: "EE%sT",
            saving: Saving::Multiple(&rulesets::Palestine),
            start_time: Some(1220227200),
            end_time:   Some(1262304000),
        },
        Timespan {
            offset: 7200,
            format: "EET",
            saving: Saving::NoSaving,
            start_time: Some(1262304000),
            end_time:   Some(1269648060),
        },
        Timespan {
            offset: 7200,
            format: "EE%sT",
            saving: Saving::Multiple(&rulesets::Palestine),
            start_time: Some(1269648060),
            end_time:   Some(1312156800),
        },
        Timespan {
            offset: 7200,
            format: "EET",
            saving: Saving::NoSaving,
            start_time: Some(1312156800),
            end_time:   Some(1325376000),
        },
        Timespan {
            offset: 7200,
            format: "EE%sT",
            saving: Saving::Multiple(&rulesets::Palestine),
            start_time: Some(1325376000),
            end_time:   None,
        },
    ],
};


