
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "Asia/Macau",
    timespans: &[
        Timespan {
            offset: 27260,
            format: "LMT",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(-1830384000),
        },
        Timespan {
            offset: 28800,
            format: "MO%sT",
            saving: Saving::Multiple(&rulesets::Macau),
            start_time: Some(-1830384000),
            end_time:   Some(945648000),
        },
        Timespan {
            offset: 28800,
            format: "C%sT",
            saving: Saving::Multiple(&rulesets::PRC),
            start_time: Some(945648000),
            end_time:   None,
        },
    ],
};


