
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Asia/Pyongyang",
    transitions: &[
        Transition {
            occurs_at: None,
            offset: 30180,  // UTC offset 30180, DST offset 0
            name: "LMT",
        },
        Transition {
            occurs_at: Some(-1948782180),
            offset: 30600,  // UTC offset 30600, DST offset 0
            name: "KST",
        },
        Transition {
            occurs_at: Some(-1830414600),
            offset: 32400,  // UTC offset 32400, DST offset 0
            name: "JCST",
        },
        Transition {
            occurs_at: Some(-1017824400),
            offset: 32400,  // UTC offset 32400, DST offset 0
            name: "JST",
        },
        Transition {
            occurs_at: Some(-768646800),
            offset: 32400,  // UTC offset 32400, DST offset 0
            name: "KST",
        },
        Transition {
            occurs_at: Some(1439564400),
            offset: 30600,  // UTC offset 30600, DST offset 0
            name: "KST",
        },
    ],
};


