
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Asia/Sakhalin",
    transitions: ZoneSet {
        first: ZoneDetails {
            offset: 34248,  // UTC offset 34248, DST offset 0
            name: "LMT",
        },
        rest: &[
        (-2031039048, ZoneDetails {
            offset: 32400,  // UTC offset 32400, DST offset 0
            name: "JCST",
        }),
        (-1017824400, ZoneDetails {
            offset: 32400,  // UTC offset 32400, DST offset 0
            name: "JST",
        }),
        (-768560400, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (354891600, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (370699200, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (386427600, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (402235200, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (417963600, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (433771200, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (449586000, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (465318000, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (481042800, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (496767600, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (512492400, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (528217200, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (543942000, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (559666800, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (575391600, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (591116400, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (606841200, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (622566000, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (638290800, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (654620400, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (670345200, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (686073600, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (695750400, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (701784000, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (717505200, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (733244400, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (748969200, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (764694000, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (780418800, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (796143600, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (811868400, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (828198000, ZoneDetails {
            offset: 43200,  // UTC offset 39600, DST offset 3600
            name: "SAKST",
        }),
        (846342000, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (859647600, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (877795200, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (891100800, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (909244800, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (922550400, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (941299200, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (954000000, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (972748800, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (985449600, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1004198400, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1017504000, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1035648000, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1048953600, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1067097600, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1080403200, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1099152000, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1111852800, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1130601600, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1143302400, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1162051200, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1174752000, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1193500800, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1206806400, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1224950400, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1238256000, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1256400000, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1269705600, ZoneDetails {
            offset: 39600,  // UTC offset 36000, DST offset 3600
            name: "SAKST",
        }),
        (1288454400, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
        (1301155200, ZoneDetails {
            offset: 39600,  // UTC offset 39600, DST offset 0
            name: "SAKT",
        }),
        (1414249200, ZoneDetails {
            offset: 36000,  // UTC offset 36000, DST offset 0
            name: "SAKT",
        }),
    ]},
};


