
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use std::borrow::Cow;
use datetime::zone::{StaticTimeZone, FixedTimespanSet, FixedTimespan};

pub static ZONE: StaticTimeZone<'static> = StaticTimeZone {
    name: "Africa/Cairo",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: 7509,  // UTC offset 7509, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("LMT"),
        },
        rest: &[
        (-2185409109, FixedTimespan {  // 1900-09-30T21:54:51.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-929844000, FixedTimespan {  // 1940-07-14T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-923108400, FixedTimespan {  // 1940-09-30T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-906170400, FixedTimespan {  // 1941-04-14T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-892868400, FixedTimespan {  // 1941-09-15T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-875844000, FixedTimespan {  // 1942-03-31T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-857790000, FixedTimespan {  // 1942-10-26T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-844308000, FixedTimespan {  // 1943-03-31T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-825822000, FixedTimespan {  // 1943-10-31T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-812685600, FixedTimespan {  // 1944-03-31T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-794199600, FixedTimespan {  // 1944-10-31T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-779853600, FixedTimespan {  // 1945-04-15T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-762663600, FixedTimespan {  // 1945-10-31T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-399088800, FixedTimespan {  // 1957-05-09T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-386650800, FixedTimespan {  // 1957-09-30T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-368330400, FixedTimespan {  // 1958-04-30T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-355114800, FixedTimespan {  // 1958-09-30T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-336790800, FixedTimespan {  // 1959-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-323654400, FixedTimespan {  // 1959-09-30T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-305168400, FixedTimespan {  // 1960-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-292032000, FixedTimespan {  // 1960-09-30T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-273632400, FixedTimespan {  // 1961-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-260496000, FixedTimespan {  // 1961-09-30T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-242096400, FixedTimespan {  // 1962-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-228960000, FixedTimespan {  // 1962-09-30T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-210560400, FixedTimespan {  // 1963-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-197424000, FixedTimespan {  // 1963-09-30T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-178938000, FixedTimespan {  // 1964-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-165801600, FixedTimespan {  // 1964-09-30T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-147402000, FixedTimespan {  // 1965-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-134265600, FixedTimespan {  // 1965-09-30T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-115866000, FixedTimespan {  // 1966-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-102643200, FixedTimespan {  // 1966-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-84330000, FixedTimespan {  // 1967-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-71107200, FixedTimespan {  // 1967-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-52707600, FixedTimespan {  // 1968-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-39484800, FixedTimespan {  // 1968-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (-21171600, FixedTimespan {  // 1969-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (-7948800, FixedTimespan {  // 1969-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (10364400, FixedTimespan {  // 1970-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (23587200, FixedTimespan {  // 1970-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (41900400, FixedTimespan {  // 1971-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (55123200, FixedTimespan {  // 1971-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (73522800, FixedTimespan {  // 1972-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (86745600, FixedTimespan {  // 1972-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (105058800, FixedTimespan {  // 1973-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (118281600, FixedTimespan {  // 1973-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (136594800, FixedTimespan {  // 1974-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (149817600, FixedTimespan {  // 1974-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (168130800, FixedTimespan {  // 1975-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (181353600, FixedTimespan {  // 1975-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (199753200, FixedTimespan {  // 1976-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (212976000, FixedTimespan {  // 1976-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (231289200, FixedTimespan {  // 1977-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (244512000, FixedTimespan {  // 1977-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (262825200, FixedTimespan {  // 1978-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (276048000, FixedTimespan {  // 1978-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (294361200, FixedTimespan {  // 1979-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (307584000, FixedTimespan {  // 1979-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (325983600, FixedTimespan {  // 1980-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (339206400, FixedTimespan {  // 1980-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (357519600, FixedTimespan {  // 1981-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (370742400, FixedTimespan {  // 1981-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (396399600, FixedTimespan {  // 1982-07-24T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (402278400, FixedTimespan {  // 1982-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (426812400, FixedTimespan {  // 1983-07-11T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (433814400, FixedTimespan {  // 1983-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (452214000, FixedTimespan {  // 1984-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (465436800, FixedTimespan {  // 1984-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (483750000, FixedTimespan {  // 1985-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (496972800, FixedTimespan {  // 1985-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (515286000, FixedTimespan {  // 1986-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (528508800, FixedTimespan {  // 1986-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (546822000, FixedTimespan {  // 1987-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (560044800, FixedTimespan {  // 1987-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (578444400, FixedTimespan {  // 1988-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (591667200, FixedTimespan {  // 1988-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (610412400, FixedTimespan {  // 1989-05-05T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (623203200, FixedTimespan {  // 1989-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (641516400, FixedTimespan {  // 1990-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (654739200, FixedTimespan {  // 1990-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (673052400, FixedTimespan {  // 1991-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (686275200, FixedTimespan {  // 1991-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (704674800, FixedTimespan {  // 1992-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (717897600, FixedTimespan {  // 1992-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (736210800, FixedTimespan {  // 1993-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (749433600, FixedTimespan {  // 1993-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (767746800, FixedTimespan {  // 1994-04-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (780969600, FixedTimespan {  // 1994-10-01T00:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (799020000, FixedTimespan {  // 1995-04-27T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (812322000, FixedTimespan {  // 1995-09-28T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (830469600, FixedTimespan {  // 1996-04-25T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (843771600, FixedTimespan {  // 1996-09-26T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (861919200, FixedTimespan {  // 1997-04-24T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (875221200, FixedTimespan {  // 1997-09-25T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (893368800, FixedTimespan {  // 1998-04-23T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (906670800, FixedTimespan {  // 1998-09-24T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (925423200, FixedTimespan {  // 1999-04-29T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (938725200, FixedTimespan {  // 1999-09-30T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (956872800, FixedTimespan {  // 2000-04-27T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (970174800, FixedTimespan {  // 2000-09-28T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (988322400, FixedTimespan {  // 2001-04-26T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1001624400, FixedTimespan {  // 2001-09-27T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1019772000, FixedTimespan {  // 2002-04-25T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1033074000, FixedTimespan {  // 2002-09-26T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1051221600, FixedTimespan {  // 2003-04-24T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1064523600, FixedTimespan {  // 2003-09-25T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1083276000, FixedTimespan {  // 2004-04-29T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1096578000, FixedTimespan {  // 2004-09-30T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1114725600, FixedTimespan {  // 2005-04-28T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1128027600, FixedTimespan {  // 2005-09-29T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1146175200, FixedTimespan {  // 2006-04-27T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1158872400, FixedTimespan {  // 2006-09-21T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1177624800, FixedTimespan {  // 2007-04-26T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1189112400, FixedTimespan {  // 2007-09-06T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1209074400, FixedTimespan {  // 2008-04-24T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1219957200, FixedTimespan {  // 2008-08-28T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1240524000, FixedTimespan {  // 2009-04-23T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1250802000, FixedTimespan {  // 2009-08-20T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1272578400, FixedTimespan {  // 2010-04-29T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1281474000, FixedTimespan {  // 2010-08-10T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1284069600, FixedTimespan {  // 2010-09-09T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1285880400, FixedTimespan {  // 2010-09-30T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1400191200, FixedTimespan {  // 2014-05-15T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1403816400, FixedTimespan {  // 2014-06-26T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
        (1406844000, FixedTimespan {  // 2014-07-31T22:00:00.000 UTC
            offset: 10800,  // UTC offset 7200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EEST"),
        }),
        (1411678800, FixedTimespan {  // 2014-09-25T21:00:00.000 UTC
            offset: 7200,  // UTC offset 7200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EET"),
        }),
    ]},
};


