
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Africa/Khartoum",
    transitions: &[
        Transition {
            occurs_at: None,
            offset: 7808,  // UTC offset 7808, DST offset 0
            name: "LMT",
        },
        Transition {
            occurs_at: Some(-1230775808),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(10360800),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(24786000),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(41810400),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(56322000),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(73432800),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(87944400),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(104882400),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(119480400),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(136332000),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(151016400),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(167781600),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(182552400),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(199231200),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(214174800),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(230680800),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(245710800),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(262735200),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(277246800),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(294184800),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(308782800),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(325634400),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(340405200),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(357084000),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(371941200),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(388533600),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(403477200),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(419983200),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(435013200),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(452037600),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(466635600),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(483487200),
            offset: 10800,  // UTC offset 7200, DST offset 3600
            name: "CAST",
        },
        Transition {
            occurs_at: Some(498171600),
            offset: 7200,  // UTC offset 7200, DST offset 0
            name: "CAT",
        },
        Transition {
            occurs_at: Some(947930400),
            offset: 10800,  // UTC offset 10800, DST offset 0
            name: "EAT",
        },
    ],
};


