
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "Africa/Nairobi",
    timespans: &[
        Timespan {
            offset: 8836,
            format: "LMT",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(-1309737600),
        },
        Timespan {
            offset: 10800,
            format: "EAT",
            saving: Saving::NoSaving,
            start_time: Some(-1309737600),
            end_time:   Some(-1262304000),
        },
        Timespan {
            offset: 9000,
            format: "BEAT",
            saving: Saving::NoSaving,
            start_time: Some(-1262304000),
            end_time:   Some(-946771200),
        },
        Timespan {
            offset: 9900,
            format: "BEAUT",
            saving: Saving::NoSaving,
            start_time: Some(-946771200),
            end_time:   Some(-315619200),
        },
        Timespan {
            offset: 10800,
            format: "EAT",
            saving: Saving::NoSaving,
            start_time: Some(-315619200),
            end_time:   None,
        },
    ],
};


