
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use std::borrow::Cow;
use datetime::zone::{StaticTimeZone, FixedTimespanSet, FixedTimespan};

pub static ZONE: StaticTimeZone<'static> = StaticTimeZone {
    name: "Atlantic/Stanley",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: -7716,  // UTC offset -7716, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("LMT"),
        },
        rest: &[
        (-2524513884, FixedTimespan {  // 1890-00-01T2-08-36 UTC
            offset: -7716,  // UTC offset -7716, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("SMT"),
        }),
        (-1824241884, FixedTimespan {  // 1912-02-12T2-08-36 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (-1018209600, FixedTimespan {  // 1937-08-26T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (-1003093200, FixedTimespan {  // 1938-02-20T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (-986760000, FixedTimespan {  // 1938-08-25T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (-971643600, FixedTimespan {  // 1939-02-19T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (-954705600, FixedTimespan {  // 1939-09-01T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (-939589200, FixedTimespan {  // 1940-02-24T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (-923256000, FixedTimespan {  // 1940-08-29T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (-908139600, FixedTimespan {  // 1941-02-23T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (-891806400, FixedTimespan {  // 1941-08-28T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (-876690000, FixedTimespan {  // 1942-02-22T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (-860356800, FixedTimespan {  // 1942-08-27T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (-852066000, FixedTimespan {  // 1943-00-01T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (420609600, FixedTimespan {  // 1983-04-01T4-00-00 UTC
            offset: -10800,  // UTC offset -10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (433306800, FixedTimespan {  // 1983-08-25T3-00-00 UTC
            offset: -7200,  // UTC offset -10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (452052000, FixedTimespan {  // 1984-03-29T2-00-00 UTC
            offset: -10800,  // UTC offset -10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (464151600, FixedTimespan {  // 1984-08-16T3-00-00 UTC
            offset: -7200,  // UTC offset -10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (483501600, FixedTimespan {  // 1985-03-28T2-00-00 UTC
            offset: -10800,  // UTC offset -10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (495601200, FixedTimespan {  // 1985-08-15T3-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (514350000, FixedTimespan {  // 1986-03-20T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (527054400, FixedTimespan {  // 1986-08-14T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (545799600, FixedTimespan {  // 1987-03-19T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (558504000, FixedTimespan {  // 1987-08-13T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (577249200, FixedTimespan {  // 1988-03-17T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (589953600, FixedTimespan {  // 1988-08-11T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (608698800, FixedTimespan {  // 1989-03-16T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (621403200, FixedTimespan {  // 1989-08-10T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (640753200, FixedTimespan {  // 1990-03-22T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (652852800, FixedTimespan {  // 1990-08-09T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (672202800, FixedTimespan {  // 1991-03-21T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (684907200, FixedTimespan {  // 1991-08-15T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (703652400, FixedTimespan {  // 1992-03-19T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (716356800, FixedTimespan {  // 1992-08-13T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (735102000, FixedTimespan {  // 1993-03-18T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (747806400, FixedTimespan {  // 1993-08-12T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (766551600, FixedTimespan {  // 1994-03-17T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (779256000, FixedTimespan {  // 1994-08-11T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (798001200, FixedTimespan {  // 1995-03-16T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (810705600, FixedTimespan {  // 1995-08-10T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (830055600, FixedTimespan {  // 1996-03-21T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (842760000, FixedTimespan {  // 1996-08-15T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (861505200, FixedTimespan {  // 1997-03-20T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (874209600, FixedTimespan {  // 1997-08-14T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (892954800, FixedTimespan {  // 1998-03-19T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (905659200, FixedTimespan {  // 1998-08-13T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (924404400, FixedTimespan {  // 1999-03-18T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (937108800, FixedTimespan {  // 1999-08-12T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (955854000, FixedTimespan {  // 2000-03-16T3-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (968558400, FixedTimespan {  // 2000-08-10T4-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (987310800, FixedTimespan {  // 2001-03-15T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (999410400, FixedTimespan {  // 2001-08-02T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1019365200, FixedTimespan {  // 2002-03-21T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1030860000, FixedTimespan {  // 2002-08-01T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1050814800, FixedTimespan {  // 2003-03-20T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1062914400, FixedTimespan {  // 2003-08-07T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1082264400, FixedTimespan {  // 2004-03-18T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1094364000, FixedTimespan {  // 2004-08-05T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1113714000, FixedTimespan {  // 2005-03-17T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1125813600, FixedTimespan {  // 2005-08-04T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1145163600, FixedTimespan {  // 2006-03-16T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1157263200, FixedTimespan {  // 2006-08-03T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1176613200, FixedTimespan {  // 2007-03-15T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1188712800, FixedTimespan {  // 2007-08-02T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1208667600, FixedTimespan {  // 2008-03-20T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1220767200, FixedTimespan {  // 2008-08-07T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1240117200, FixedTimespan {  // 2009-03-19T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1252216800, FixedTimespan {  // 2009-08-06T6-00-00 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("FKST"),
        }),
        (1271566800, FixedTimespan {  // 2010-03-18T5-00-00 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKT"),
        }),
        (1283666400, FixedTimespan {  // 2010-08-05T6-00-00 UTC
            offset: -10800,  // UTC offset -10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("FKST"),
        }),
    ]},
};


