
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "America/Atikokan",
    transitions: ZoneSet {
        first: ZoneDetails {
            offset: -21212,  // UTC offset -21212, DST offset 0
            name: "LMT",
        },
        rest: &[
        (-2366733988, ZoneDetails {
            offset: -21600,  // UTC offset -21600, DST offset 0
            name: "CST",
        }),
        (-1632067200, ZoneDetails {
            offset: -18000,  // UTC offset -21600, DST offset 3600
            name: "CDT",
        }),
        (-1615136400, ZoneDetails {
            offset: -21600,  // UTC offset -21600, DST offset 0
            name: "CST",
        }),
        (-923248800, ZoneDetails {
            offset: -18000,  // UTC offset -21600, DST offset 3600
            name: "CDT",
        }),
        (-880218000, ZoneDetails {
            offset: -18000,  // UTC offset -21600, DST offset 3600
            name: "CWT",
        }),
        (-769395600, ZoneDetails {
            offset: -18000,  // UTC offset -21600, DST offset 3600
            name: "CPT",
        }),
        (-765392400, ZoneDetails {
            offset: -18000,  // UTC offset -18000, DST offset 0
            name: "EST",
        }),
    ]},
};


