
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use std::borrow::Cow;
use datetime::zone::{StaticTimeZone, FixedTimespanSet, FixedTimespan};

pub static ZONE: StaticTimeZone<'static> = StaticTimeZone {
    name: "America/Caracas",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: -12736,  // UTC offset -12736, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("LMT"),
        },
        rest: &[
        (-2524508864, FixedTimespan {  // 1890-01-01T03:32:16.000 UTC
            offset: -12740,  // UTC offset -12740, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CMT"),
        }),
        (-1826742460, FixedTimespan {  // 1912-02-12T03:32:20.000 UTC
            offset: -12600,  // UTC offset -12600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("VET"),
        }),
        (-157753800, FixedTimespan {  // 1965-01-01T03:30:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("VET"),
        }),
        (1197183600, FixedTimespan {  // 2007-12-09T07:00:00.000 UTC
            offset: -12600,  // UTC offset -12600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("VET"),
        }),
    ]},
};


