
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "America/Dawson_Creek",
    timespans: &[
        Timespan {
            offset: -28744,
            format: "LMT",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(-2713910400),
        },
        Timespan {
            offset: -28800,
            format: "P%sT",
            saving: Saving::Multiple(&rulesets::Canada),
            start_time: Some(-2713910400),
            end_time:   Some(-725846400),
        },
        Timespan {
            offset: -28800,
            format: "P%sT",
            saving: Saving::Multiple(&rulesets::Vanc),
            start_time: Some(-725846400),
            end_time:   Some(83988000),
        },
        Timespan {
            offset: -25200,
            format: "MST",
            saving: Saving::NoSaving,
            start_time: Some(83988000),
            end_time:   None,
        },
    ],
};


