
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "America/Denver",
    timespans: &[
        Timespan {
            offset: -18004,
            format: "LMT",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(-2717668796),
        },
        Timespan {
            offset: -25200,
            format: "M%sT",
            saving: Saving::Multiple(&rulesets::US),
            start_time: Some(-2717668796),
            end_time:   Some(-1577923200),
        },
        Timespan {
            offset: -25200,
            format: "M%sT",
            saving: Saving::Multiple(&rulesets::Denver),
            start_time: Some(-1577923200),
            end_time:   Some(-883612800),
        },
        Timespan {
            offset: -25200,
            format: "M%sT",
            saving: Saving::Multiple(&rulesets::US),
            start_time: Some(-883612800),
            end_time:   Some(-757382400),
        },
        Timespan {
            offset: -25200,
            format: "M%sT",
            saving: Saving::Multiple(&rulesets::Denver),
            start_time: Some(-757382400),
            end_time:   Some(-94694400),
        },
        Timespan {
            offset: -25200,
            format: "M%sT",
            saving: Saving::Multiple(&rulesets::US),
            start_time: Some(-94694400),
            end_time:   None,
        },
    ],
};


