
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "America/Tegucigalpa",
    transitions: ZoneSet {
        first: ZoneDetails {
            offset: -15068,  // UTC offset -15068, DST offset 0
            name: "LMT",
        },
        rest: &[
        (-1538509732, ZoneDetails {
            offset: -21600,  // UTC offset -21600, DST offset 0
            name: "CST",
        }),
        (547020000, ZoneDetails {
            offset: -18000,  // UTC offset -21600, DST offset 3600
            name: "CDT",
        }),
        (559717200, ZoneDetails {
            offset: -21600,  // UTC offset -21600, DST offset 0
            name: "CST",
        }),
        (578469600, ZoneDetails {
            offset: -18000,  // UTC offset -21600, DST offset 3600
            name: "CDT",
        }),
        (591166800, ZoneDetails {
            offset: -21600,  // UTC offset -21600, DST offset 0
            name: "CST",
        }),
        (1146981600, ZoneDetails {
            offset: -18000,  // UTC offset -21600, DST offset 3600
            name: "CDT",
        }),
        (1154926800, ZoneDetails {
            offset: -21600,  // UTC offset -21600, DST offset 0
            name: "CST",
        }),
    ]},
};


