
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;
use datetime::zoned::zoneinfo::Saving::*;

#[allow(unused_imports)]
use data::rulesets;

pub const ZONE: Zone<'static> = Zone {
    name: "Australia/Perth",
    timespans: &[
        Timespan {
            offset: 27804,
            format: "LMT",
            saving: Saving::NoSaving,
            start_time: None,
            end_time:   Some(-2337897600),
        },
        Timespan {
            offset: 28800,
            format: "AW%sT",
            saving: Saving::Multiple(&rulesets::Aus),
            start_time: Some(-2337897600),
            end_time:   Some(-836438400),
        },
        Timespan {
            offset: 28800,
            format: "AW%sT",
            saving: Saving::Multiple(&rulesets::AW),
            start_time: Some(-836438400),
            end_time:   None,
        },
    ],
};


