
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use datetime::zoned::zoneinfo::*;

pub const ZONE: Zone<'static> = Zone {
    name: "Australia/Perth",
    transitions: ZoneSet {
        first: ZoneDetails {
            offset: 27804,  // UTC offset 27804, DST offset 0
            name: "LMT",
        },
        rest: &[
        (-2337925404, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (-1672559940, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (-1665385200, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (-883634400, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (-876121200, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (-860392800, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (-844671600, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (152042400, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (162928800, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (436298400, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (447184800, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (690314400, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (699472800, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (1165082400, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (1174759200, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (1193508000, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (1206813600, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
        (1224957600, ZoneDetails {
            offset: 32400,  // UTC offset 28800, DST offset 3600
            name: "AWDT",
        }),
        (1238263200, ZoneDetails {
            offset: 28800,  // UTC offset 28800, DST offset 0
            name: "AWST",
        }),
    ]},
};


